tf_state_bucket_name_prod        = "terraform-state-bucket-eliran-prod"
tf_app_data_bucket_name_prod    = "data-bucket-eliran-prod"
sqs_queue_name                  = "prod-data-queue"
vpc_name                        = "vpc-prod"
vpc_cidr                        = "10.0.0.0/16"
subnet_cidr                     = "10.0.1.0/24"
# elb_name                        = "eliran-prod-alb"
# ecs_cluster_name                = "eliran-prod-cluster"