variable "s3_bucket_name" { type = string }
variable "sqs_queue_name" { type = string }
variable "vpc_name" { type = string }
variable "vpc_cidr" { type = string }
variable "subnet_cidr_a" { type = string }
variable "subnet_cidr_b" { type = string }
variable "subnet_cidr_private_a" { type = string }
variable "subnet_cidr_private_b" { type = string }
variable "region" { type = string }
variable "alb_name" { type = string }
# variable "ecs_cluster_name" { type = string }